name: TreeGen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.11
  - tensorflow-gpu==1.13.1
  - cudatoolkit==10.0.130
  - cudnn==7.6.0
  - numpy==1.16.6
  - tqdm==4.31.1
  - nltk==3.3.0
  - pip
#  - pip:

#   - nltk==3.2.1
